[package]
name = "smog"
version = "0.0.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "A Noise implementation focus on one-rtt and zero-rtt handshake."

[dependencies]
